channels:
- conda-forge
dependencies:
- pandas=1.2.2
- seaborn=0.11.1
- jupyter=1.0.0
- notebook=6.2.0
- scikit-bio=0.5.6
- statsmodels=0.12.2
- scipy=1.6.0
- pystan=2.19.1
- pip:
  - cmdstanpy==0.9.68
